<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-13 18:45:34
 * @@Modify Date: 2018-03-12 00:13:22
 * @@Function:
 */

$classer = $this->getData('el_class');
?>
<div id="footer-copyright" class="<?php echo esc_attr($classer) ?>">
        <div class="license">
            <address>&copy;<?php echo __('2018 Copyright. All rights reserved.Design by', 'alothemes') ?> <a class="active" href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php echo __('Bigsale', 'alothemes') ?></a>
            </address>
        </div>
</div>

