<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-12 11:29:45
 * @@Modify Date: 2017-12-08 11:35:43
 * @@Function:
 */

$menu       = $this->getData('menu');
$depth      = $this->getData('depth');
$classer   = $this->getData('el_class');
$_type = has_nav_menu($menu) ? 'theme_location' : 'menu';
global $navmobile;
$menus = explode( ',', $menu );
?>
<div class="nav-mobile-wrap">
    <div id="mobileSidenav" class="sidenav menu menu-mobile">
        <a href="javascript:void(0)" class="closebtn">&times;</a>
        <div class="nav-mobile navigation-mobile clearfix">
            <ul class="menu-wrap" >
            <?php
                foreach ($menus as $menu) {
                    echo isset($navmobile[$menu]) ? $navmobile[$menu] : $this->getMobileHtml($menu);
                }
            ?> 
            </ul>
        </div>
    </div>
    <div class="nav-mobile-overlay-fixed"></div>
</div>
