<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-13 18:45:34
 * @@Modify Date: 2018-03-12 00:14:08
 * @@Function:
 */

$classer = $this->getData('el_class');
?>
<div class="newsletter">
    <div class="tnp tnp-widget-minimal <?php echo esc_attr($classer) ?>">
        <form action="<?php echo esc_url( home_url( '/' ) ) . '?na=s';  ?>" method="post" id="newsletter-validate-detail">
                <div class="block-title"><span class="title"><?php echo __('Newsletter', 'alothemes'); ?>:</span></div>
                <div class="form-subscribe clearfix">
                	<div class="input-box">
                    	<input type="hidden" name="nr" value="widget-minimal"/>
                    	<input type="email" required name="ne" id="newsletter" value="" title="<?php echo esc_attr__('Sign up for our newsletter', 'alothemes'); ?>" placeholder="<?php echo esc_attr__('Your email', 'alothemes'); ?>" class="tnp-email">
                	</div>
                	<div class="actions">
                		<button type="submit" title="<?php echo esc_attr__('Subscribe', 'alothemes'); ?>" class="tnp-submit"><?php echo __('Subscribe', 'alothemes'); ?></button>
                	</div>
                </div>
        </form>
    </div>
</div><!-- end newsletter -->
