<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2018-06-14 00:03:36
 * @@Modify Date: 2018-06-14 01:27:38
 * @@Function:
 */

$options = $this->getOptions();
$selector = 'alo-content-'.rand(0,999999999);
?>
<div class="box-brand">
    <div class="<?php echo esc_attr($selector) ?> magicproduct autoplay">   
        <div class="title-tab"><h3 class="title"><?php  echo __('Shop by Brand', 'aloexpert'); ?></h3></div>
        <div class="magictabs" data-ajax='{"limit":"<?php echo $this->getData('limit') ?> ","timer":"<?php echo $this->getData('timer') ?>","cart":"<?php echo $this->getData('cart') ?>","compare":"<?php echo $this->getData('compare') ?>","wishlist":"<?php echo $this->getData('wishlist') ?>","review":"<?php echo $this->getData('review') ?>"}' >
            <div class="shopbrand" <?php foreach($options as $key => $value){?>
                                                   data-<?php echo esc_attr($key); ?>='<?php echo esc_attr($value); ?>'
                                           <?php } ?> >
                        <?php
                            $activated = 'activated';  
                            foreach($this->_brands as  $item){
                                if($activated){
                                    $status = "activated loaded";
                                    $activated = '';
                                } else $status = '';
                                $type = $item['brand'];
                                echo '<div class="item type-product ' . $status . '" data-type ="'.$type.'" ><div class="img-brand"><img src="' . esc_url($item['img']) . '" alt="' . esc_attr($item['name']) . '" /></div></div>';
                            }
                        ?>
            </div>            
        </div>
        <div class="ajax_loading" style="display:none" data-url="<?php echo admin_url( 'admin-ajax.php' ); ?>"  data-action="magiccart_shopbrand"></div>
        <div class="block-content clearfix">
            <div class="content-products-featured">
                <div class="content-products" 
                    data-padding="15" 
                    data-autoplay="false" 
                    data-arrows="true" 
                    data-dots="false" 
                    data-infinite="true"
                    data-slides-to-show="3" 
                    data-responsive='[{"breakpoint": "1201", "settings":{"slidesToShow":"3"}}, {"breakpoint": "1200", "settings":{"slidesToShow":"2"}}, {"breakpoint": "992", "settings":{"slidesToShow":"2"}}, {"breakpoint": "768", "settings":{"slidesToShow":"2"}}, {"breakpoint": "641", "settings":{"slidesToShow":"2"}}, {"breakpoint": "481", "settings":{"slidesToShow":"1"}}, {"breakpoint": "361", "settings":{"slidesToShow":"1"}}]'
                    data-rows="1" 
                    data-autoplay-speed="3000" 
                    data-vertical="false" 
                    data-vertical-swiping="false" 
                    data-swipe-to-slide="true"
                > 
                    <?php
                        $grid = $this->getTemplateFile('shopbrand/grid.phtml'); 
                        foreach($this->_products as $key => $collection){ 
                            include $grid; 
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
    (function ($) {
        var shopbrand  = $('.<?php echo $selector ?> .shopbrand');
        if(shopbrand.length) $('head').append(magicproduct(shopbrand, '.item'));
    })(jQuery);
});
</script>
